name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  log_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log message
        run: echo "Hello, World! debug"