name: ListingBucket

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  listing_buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_PIPELINEROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: List S3 Buckets
        run: |
          echo "Listing all S3 buckets in the account"
          aws s3 ls